name: frb_test
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  ffigen: ^7.2.4
  lints: ^2.0.0
  test: ^1.16.0
  freezed: 2.3.2
  build_runner: 2.3.3

dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.64.0
  freezed_annotation: 2.2.0
